CONFIG_GPIO=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_SENSOR=y
CONFIG_I2C=y

# UART1 and I2C1 share hardware on the nRF5340. Use UART0 for TF-M logging.
CONFIG_TFM_SECURE_UART=y
CONFIG_TFM_SECURE_UART0=y

CONFIG_SUM_PRINT=y
