# SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
# SPDX-License-Identifier: Apache-2.0

# Populate the bootloader partition used by the non-secure board target.
SB_CONFIG_BOOTLOADER_MCUBOOT=y
